name: Check if Any Label is Attached to Pull Request

on:
  pull_request:
    types:
      - synchronize  # PR에 변경 사항이 있는 경우 실행

jobs:
  check-label:
    runs-on: ubuntu-latest

    steps:
    - name: Check for any label
      id: check-label
      env:
        PR_NUMBER: ${{ github.event.pull_request.number }}  # PR 번호를 가져옵니다
      run: |
        # GitHub API를 사용하여 PR의 라벨을 확인
        echo "${{ github.event.pull_request.number }}"
        echo "${{ github.repository }}"
        labels=$(curl -s -H "Authorization: token ${{ secrets.GH_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/labels" | jq -r '.[].name')

        if [ -n "$labels" ]; then
          echo "라벨이 존재합니다."
        else
          echo "라벨이 존재하지 않습니다."
          exit 1
        fi