name: Update Mergeability on Label

on:
  pull_request:
    types:
      - synchronize  # PR에 변경 사항이 있는 경우 실행

jobs:
  update-mergeability:
    runs-on: ubuntu-latest

    steps:
    - name: Check for required label
      id: check-label
      run: |
        # GitHub API를 사용하여 PR의 라벨 존재 확인
        labels=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/labels" | jq -r '.[].name')

        if [ -n "$labels" ]; then
          echo "라벨이 존재합니다. 머지 가능한 상태로 변경합니다."
          curl -X PATCH -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -d '{"mergeable": true}' "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}"
        else
          echo "라벨이 존재하지 않습니다."
        fi
